# Generated by Django 3.1.2 on 2020-11-19 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_first_name', models.CharField(max_length=50)),
                ('employee_title', models.CharField(max_length=100)),
                ('employee_last_name', models.CharField(max_length=50)),
                ('employee_area_code', models.CharField(max_length=3)),
                ('employee_phone_number', models.CharField(max_length=50)),
                ('employee_pronoun_list', models.CharField(blank=True, choices=[('a', 'They / Them'), ('b', 'She / Her / Hers'), ('c', 'He / Him / His'), ('d', 'Other, please specify')], max_length=1)),
                ('employee_pronoun_other', models.CharField(blank=True, max_length=50)),
                ('employee_address', models.CharField(blank=True, choices=[('a', '9500 NE Cascades Pkwy, Portland, OR 97220'), ('b', '17014 NE Sandy Blvd., Portland, OR 97230'), ('c', '508 S. Boston Ave., Tulsa, OK 74103'), ('d', 'Portland, Oregon'), ('e', 'Tulsa, Oklahoma'), ('f', 'Other, please specify')], max_length=1)),
                ('employee_address_other1', models.CharField(blank=True, max_length=100)),
                ('employee_address_other2', models.CharField(blank=True, max_length=100)),
                ('employee_zoomid', models.CharField(blank=True, max_length=50)),
                ('employee_profile_pic', models.ImageField(blank=True, null=True, upload_to='')),
                ('url', models.SlugField(blank=True, max_length=500)),
            ],
        ),
    ]
